name: module17_ml
channels:
  - conda-forge
dependencies:
  - python           =3.10
  - imbalanced-learn =0.9.*
  - jupyterlab       =3.4.*
  - pandas           =1.4.*
  - numpy            =1.22.*
  - scikit-learn     =1.1.*
